"use strict";
exports.__esModule = true;
var professional_1 = require("./professional");
var movie_1 = require("./movie");
var imdb_1 = require("./imdb");
var Profession;
(function (Profession) {
    Profession[Profession["director"] = 0] = "director";
    Profession[Profession["guionista"] = 1] = "guionista";
    Profession[Profession["actor"] = 2] = "actor";
})(Profession || (Profession = {}));
;
var julia = new professional_1.Professional("Julia Roberth", 23, "Mujer", 65, 165, "Negro", "Azules", "Caucacica", true, "Americana", 4, Profession.actor);
var will = new professional_1.Professional("Will Smith", 50, "hombre", 65, 165, "Negro", "Azules", "Negro", true, "Americana", 20, Profession.actor);
var matthew = new professional_1.Professional("Matthew McConaughey", 45, "hombre", 65, 175, "Negro", "negro", "Negro", true, "Americano", 4, Profession.actor);
var jason = new professional_1.Professional("Jason Sth", 55, "hombre", 58, 180, "Blanco", "negro", "Negro", false, "Americano", 4, Profession.actor);
var helen = new professional_1.Professional("Helen Hunt", 45, "hombre", 65, 175, "Negro", "negro", "Negro", true, "Americana", 4, Profession.guionista);
var paz = new professional_1.Professional("Paz Vega", 45, "Mujer", 65, 175, "blanca", "negro", "Negro", false, "Española", 4, Profession.director);
var Sharknado = new movie_1.Movie("Sharknado", 2011, "USA", "Z");
var Panther = new movie_1.Movie("Black Panther", 2016, "France", "Heroes");
var Doctor = new movie_1.Movie("Doctor Strange", 2014, "Italian", "Thriller");
var movies = [Sharknado, Panther, Doctor];
var prueba = new imdb_1.Imdb(movies);
Sharknado.actors = [julia, will];
Sharknado.director = paz;
Sharknado.writer = helen;
Sharknado.language = "English";
Sharknado.platform = "Netflix";
Sharknado.isMCU = false;
Sharknado.mainCharacterName = "Phinley";
Sharknado.producer = "Firenado+";
Sharknado.distributor = "Cool surreal films";
Panther.actors = [matthew, jason];
Panther.director = paz;
Panther.writer = helen;
Panther.language = "French";
Panther.platform = "Golden";
Panther.isMCU = true;
Panther.mainCharacterName = "Georgina";
Panther.producer = "Camp";
Panther.distributor = "Look at this fish";
Doctor.actors = [julia, matthew, jason];
Doctor.director = paz;
Doctor.writer = helen;
Doctor.language = "Italian";
Doctor.platform = "Livin";
Doctor.isMCU = false;
Doctor.mainCharacterName = "Frances";
Doctor.producer = "Fresh";
Doctor.distributor = "What the hell!";
console.log(Sharknado.mostrarDatos());
console.log(prueba.films[0].mostrarDatos());
console.log(prueba.films[1].mostrarDatos());
console.log(prueba.films[2].mostrarDatos());
